package dk.mhr.radio8podcast.service

class MockFetchPodcastById {

    val mockData = """
        {
        "id": "8ade9927c58244859e7c363d055c9584",
        "title": "r8Dio - Undskyld vi roder",
        "publisher": "r8Dio",
        "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
        "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
        "listennotes_url": "https:\/\/www.listennotes.com\/c\/8ade9927c58244859e7c363d055c9584\/",
        "listen_score": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
        "listen_score_global_rank": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
        "total_episodes": 153,
        "audio_length_sec": 2959,
        "update_frequency_hours": 168,
        "explicit_content": false,
        "description": "<p>I denne udsendelsesr&aelig;kke f&oslash;lger vi tilblivelsen af r8Dio - Danmarks nye snakke-sludre-taleradio. Det er en dokumentaristisk behind-the-scenes f&oslash;ljeton, der giver et indblik i det store arbejde med at skabe en landsd&aelig;kkende radio.&nbsp;<\/p>",
        "itunes_id": 1519404116,
        "rss": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
        "latest_pub_date_ms": 1679032800000,
        "latest_episode_id": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
        "earliest_pub_date_ms": 1591108380143,
        "language": "Danish",
        "country": "Denmark",
        "website": "https:\/\/www.r8dio.dk?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "extra": {
          "twitter_handle": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "facebook_handle": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "instagram_handle": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "wechat_handle": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "patreon_handle": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "youtube_url": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "linkedin_url": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "spotify_url": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "google_url": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "amazon_music_url": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "url1": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "url2": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
          "url3": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing"
        },
        "is_claimed": false,
        "email": "Please upgrade to PRO or ENTERPRISE plan to see this field. Learn more: listennotes.com\/api\/pricing",
        "type": "episodic",
        "looking_for": {
          "sponsors": false,
          "guests": false,
          "cohosts": false,
          "cross_promotion": false
        },
        "genre_ids": [
          67,
          133
        ],
        "episodes": [
          {
            "id": "5920e52b93e74e48824dace4ae1e55b2",
            "title": "Afsnit 153 - Oxy, oplæg og orgelsamler",
            "description": "<p>Klavs Bundgaard har stadig problemer med bentøjet og kontakter derfor Dorte fra Skuldborg Apotek. Det holder ham dog ikke tilbage fra at holde oplæg i Stjernen sammen med programchef Allan Sindberg og sørge for at Emil kan komme til i printerrummet på trods af den sovende orgelsamler, Mark Jann. Endelig skal han lige have en snak med Randi... Øvrige medvirkende: Morten Larsen, Gert Bendiksen og Sarah Bo.<\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1679032800000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/5920e52b93e74e48824dace4ae1e55b2\/",
            "audio_length_sec": 3361,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/5920e52b93e74e48824dace4ae1e55b2\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/5920e52b93e74e48824dace4ae1e55b2\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-153-oxy-opl-g-og-orgelsamler?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "c34e5ec9-4ab7-4a34-bf07-afc701722daa"
          },
          {
            "id": "9ed05eb2dfb249a3ae52e2884ed6c84c",
            "title": "Afsnit 152 - Vikingedåb",
            "description": "<p>Det er en stor dag i Skuldborg - Danmarks kulturelle perle. Og det er en dag hvor man mærker histories vingesus. Randi´s Troldebebs med de fire fædre skal have sin vikingedåb. Så der er dømt dåbsceremoni på gravhøjen Tamshøj, vikingeskibsoverfart på Nørresø og fest på hotellet af samme navn. <\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1678424400000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/9ed05eb2dfb249a3ae52e2884ed6c84c\/",
            "audio_length_sec": 3776,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/9ed05eb2dfb249a3ae52e2884ed6c84c\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/9ed05eb2dfb249a3ae52e2884ed6c84c\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-152-vikingeda-b?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "f11e04a6-1a69-4099-a849-afc00169ae3d"
          },
          {
            "id": "6a901615950a4def820f2e91f5f92c6e",
            "title": "Afsnit 151 - Kartoffelæggekagen",
            "description": "<p>Radiodirektør Klavs Bundgaard prøver at balancere arbejds- og fritidsliv. Derfor har han inviteret sin programchef Allan Sindberg hjem i privaten til møde og kartoffelæggekage. Jonna ringer og klager sin nød og Klavs døjer lidt med helbredet. Derfor prøver han at ringe til sin nyhedsvært Rasmus Bruun da lægen Pernille ikke er til meget hjælp. Smørstemmen forsøger at få IT-Michael til at hjælpe med at få synkroniseret sin kalender. Altimens nærmer den store barnedåbsvikingefest sig i horisonten.  <\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1677819600000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/6a901615950a4def820f2e91f5f92c6e\/",
            "audio_length_sec": 3593,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/6a901615950a4def820f2e91f5f92c6e\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/6a901615950a4def820f2e91f5f92c6e\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-151-kartoffel-ggekagen?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "345ed55b-05b4-4c63-a689-afb9017545f8"
          },
          {
            "id": "f8a011ae159e49bcaa9eecd0466c7e0f",
            "title": "Afsnit 150 - Et morgenprogram tager form",
            "description": "<p>Mens direktør Klavs Bundgaard ligger på langs er programchef og -vært Allan Sindberg igang med et sandt arbejdsraseri. Han laver dummy til r8Dio´s morgen- og signaturprogram Morgensutterne. Til det får Allan hjælp af Emil til teknik og praktik og af musikekvilibristen Adi Zukanovic til at lave lydidentitet. Det er således et helt igennem professionelt set-up der omfavner produktionen af dummyen til Morgensutterne. Og så kigger en gammel kending forbi Stjernen.<\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1677214800000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/f8a011ae159e49bcaa9eecd0466c7e0f\/",
            "audio_length_sec": 3340,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/f8a011ae159e49bcaa9eecd0466c7e0f\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/f8a011ae159e49bcaa9eecd0466c7e0f\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-150-et-morgenprogram-tager-form?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "3410c659-6fee-437f-a5fa-afb201786852"
          },
          {
            "id": "dcd0f051d594442499fe4f283472f88b",
            "title": "Afsnit 149 - Skuldborg Fastelavn Festival",
            "description": "<p>Det er ved at være tid til den årlige Skuldborg Fastelavn Festival. For i byen der huser hele Danmarks snakke- sludre- og taleradio fejrer man Fastelavn så det kan mærkes. Pladsen foran Multi- og Kulturhuset Stjernen plejer at være centrum for festlighederne. Men da man mener man har fundet \"de nye guldhorn\" i jorden foran Stjernen, er festivalen i år flyttet til p-pladsen foran verdens største Meny. Derfor er købmanden Micky blevet medarrangør sammen med den selvudnævnte kulturdronning og daglige leder af Teater Trolden, Britt Kvist og naturligvis John Frederiksen. r8Dio´s direktør Klavs Bundgaard er også en del af arrangørerne af Skuldborg Fastelavn Festival. Men Klavs bøvler med helbredet og må bede sin programchef agere stand-in. <\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1676610000000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/dcd0f051d594442499fe4f283472f88b\/",
            "audio_length_sec": 4252,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/dcd0f051d594442499fe4f283472f88b\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/dcd0f051d594442499fe4f283472f88b\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-149-skuldborg-fastelavn-festival?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "6d81788b-0e8c-4a2f-8f88-afab01670c70"
          },
          {
            "id": "e0fb0f4294094d7eac7752d8848cd59a",
            "title": "Afsnit 148 - Hvem K.A.N.?",
            "description": "<p>På trods af en blokade foran Stjernen klør Klavs og Allan på for fulde drøn.<\/p>\n<p>På den private side står den på forberedelse til vikingebarnedåb, mens der arbejdsmæssigt fokuseres på at networke - både kommercielt, kommunalt og sågar helt oppe på ministerniveau.<\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1676005200000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/e0fb0f4294094d7eac7752d8848cd59a\/",
            "audio_length_sec": 3880,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/e0fb0f4294094d7eac7752d8848cd59a\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/e0fb0f4294094d7eac7752d8848cd59a\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-148-hvem-k-a-n?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "48cf71a5-4233-48a1-af4e-afa40187022a"
          },
          {
            "id": "21d636501c944879847008699ebd8bfb",
            "title": "Afsnit 147 - Ledelsesseminar",
            "description": "<p>Der er ledelsesseminar på Hotel Nørresø. Programchef Allan Sindberg har stykket et spændende program sammen med input udefra, der skal sørge for, at der på r8Dio fortsat bliver synergeret og kommunikeret i topklasse. Der bliver dog også tid til lidt fritid og afslapning. Direktør Klavs Bundgaard har lidt fysiske udfordringer undervejs.<\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1675407278000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/21d636501c944879847008699ebd8bfb\/",
            "audio_length_sec": 4158,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/21d636501c944879847008699ebd8bfb\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/21d636501c944879847008699ebd8bfb\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-147-ledelsesseminar?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "c18bef14-6b43-4989-adb7-af9e006f4c2f"
          },
          {
            "id": "8b6a5830f71f4d199f6e9d534b603599",
            "title": "Afsnit 146 - En taburet med tre ben",
            "description": "<p>I denne episode af Undskyld Vi Roder fejrer Klavs Bundgaard og Reinhard Weibhauer at r8Dio har opkøbt 30 % af Skuldborg Bryghus. De er opsatte på at få bryggeriets øl ind hos Meny, men har Micky fået en aftale i stand hos de høje herrer hos Meny eller har han ikke? Smørstemmen træner på livets løs for at komme i form til livetouren i efteråret men har naturligvis stadig tid til at deltage. Endeligt er der kommet en dummy på et muligt nyt program i indbakken. <\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1674800666000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/8b6a5830f71f4d199f6e9d534b603599\/",
            "audio_length_sec": 3370,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/8b6a5830f71f4d199f6e9d534b603599\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/8b6a5830f71f4d199f6e9d534b603599\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-146-en-taburet-med-tre-ben?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "25d44c12-c3d6-4c40-a40b-af97006634ed"
          },
          {
            "id": "9e218fcd261d4f3d85f5bb4dfcdb8a41",
            "title": "Afsnit 145 - Klavs her, Klavs der, Klavs allevegne",
            "description": "<p>Klavs Bundgaard er her, der og allevegne. Følg ham på denne helt almindelige dag på Ambassaden, i Stjernen, til frokostmøde, til barnedåbsplanlægning... Og det er bare lidt af hvad dagen byder på for r8Dio´s kaptajn. Men hvis ikke Klavs kan holde overblikket, hvem kan så? <\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1674196473000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/9e218fcd261d4f3d85f5bb4dfcdb8a41\/",
            "audio_length_sec": 3264,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/9e218fcd261d4f3d85f5bb4dfcdb8a41\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/9e218fcd261d4f3d85f5bb4dfcdb8a41\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-145-klavs-her-klavs-der-klavs-allevegne?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "88a9c5fe-ed57-4b02-9e89-af8f017a5341"
          },
          {
            "id": "0b8d459aea6547b2acf5718f2f1d42c5",
            "title": "Afsnit 144 - Kvantus\/Q1\/Kvartalis",
            "description": "<p>R8Dio´s ledelsesteam har kvartalsstatusmøde og synergerer på højt niveau. De massive regnmængder i Skuldborg samt Stjernens nye leder giver dog visse udfordringer. Radiodirektør Klavs Bundgaard har som altid nye skibe i søen og et opkøb af Skuldborg Bryghus er bl.a. på tallerkenen som en ny mulig r8Dio ret.  <\/p><p><a href=\"https:\/\/r8dio.dk\/pages\/stot-os\" rel=\"payment\">Support the show: https:\/\/r8dio.dk\/pages\/stot-os<\/a><\/p><p>See <a href=\"https:\/\/omnystudio.com\/listener\">omnystudio.com\/listener<\/a> for privacy information.<\/p>",
            "pub_date_ms": 1673589551000,
            "audio": "https:\/\/www.listennotes.com\/e\/p\/0b8d459aea6547b2acf5718f2f1d42c5\/",
            "audio_length_sec": 4273,
            "listennotes_url": "https:\/\/www.listennotes.com\/e\/0b8d459aea6547b2acf5718f2f1d42c5\/",
            "image": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "thumbnail": "https:\/\/production.listennotes.com\/podcasts\/r8dio-undskyld-vi-roder-r8dio-97Zld0PszE6-nzMECA_0Yja.300x300.jpg",
            "maybe_audio_invalid": false,
            "listennotes_edit_url": "https:\/\/www.listennotes.com\/e\/0b8d459aea6547b2acf5718f2f1d42c5\/#edit",
            "explicit_content": false,
            "link": "https:\/\/omny.fm\/shows\/undskyld-vi-roder\/afsnit-144-kvantus-q1-kvartalis?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "guid_from_rss": "1d5c2565-1c17-4ec9-a1e2-af89005f4ea0"
          }
        ],
        "next_episode_pub_date": 1673589551000
        } 
    """

}